### PR TITLE
Fixed --help

### LINKED ISSUE #360: ArgumentParser errors for --... arguments
Sorry if I missed some update/announcement, but running v0.36.1 after a fresh install on a new host gives `ArgumentParser` errors for some basic arguments like `help` or `version`:
```
$ tart --version
CommandError(commandStack: [tart.Root], parserError: ArgumentParser.ParserError.versionRequested)

$ tart --help
CommandError(commandStack: [tart.Root], parserError: ArgumentParser.ParserError.helpRequested(visibility: ArgumentParser.ArgumentVisibility(base: ArgumentParser.ArgumentVisibility.Representation.default)))
```

And running tart without arguments returns only `--help`.

Other arguments like `list` or `prune` work fine but again, no help available.
```
$ tart help prune
CommandError(commandStack: [tart.Root, tart.Prune], parserError: ArgumentParser.ParserError.helpRequested(visibility: ArgumentParser.ArgumentVisibility(base: ArgumentParser.ArgumentVisibility.Representation.default)))
```

### PR DESCRIPTION
**Pull request by fkorotkov**
Apparently `--help` works via exceptions 🤷‍♂️

Fixes #360

### CODE REVIEW

**Comment by fkorotkov** [comment]
Saw reference of the same issue in https://github.com/tuist/tuist/pull/1250

File: Sources/tart/Root.swift [hunk 1]
```diff
@@ -96,6 +96,10 @@ struct Root: AsyncParsableCommand {
         try command.run()
       }
     } catch {
+      if exitCode(for: error).rawValue == 0 {
```
Comment (edigaryev) [inline Sources/tart/Root.swift:99]: Should we add some comment for future reference, as this looks a bit magical?

**Review by edigaryev — APPROVED** [review]

File: Sources/tart/Root.swift (hunk 1 above)
Comment (fkorotkov) [reply Sources/tart/Root.swift:99]: Would've added if not the auto-merge. Now the context will be in git history 😅😪
